"""baseline existing database schema

Revision ID: b984e56c64a5
Revises:
Create Date: 2026-01-13 18:41:29.952399

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b984e56c64a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline migration for existing database.

    This migration represents the state of the database when Alembic was initialized.
    Tables already exist, so we check before creating them.
    """
    # Check if tables already exist - if so, skip creation
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names(schema="roadbuds")

    if "users" in existing_tables:
        # Database already has tables - this is the baseline, skip all operations
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("recommendations_url", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="roadbuds",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("photo_url", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("badges", sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        schema="roadbuds",
    )
    op.create_table(
        "assistance_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("submitted_time", sa.DateTime(), nullable=False),
        sa.Column("closing_time", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assistance_type_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Active", "Taken", "Withdrawn", "Timeout", "Resolved", name="request_status", schema="roadbuds"),
            server_default=sa.text("'Active'::roadbuds.request_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistance_type_id"],
            ["roadbuds.assistance_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["roadbuds.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="roadbuds",
    )
    op.create_index(
        "idx_assistance_requests_location",
        "assistance_requests",
        ["location"],
        unique=False,
        schema="roadbuds",
        postgresql_using="gist",
    )
    op.create_table(
        "settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notify_on_request", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notify_on_offer", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["roadbuds.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        schema="roadbuds",
    )
    op.create_table(
        "user_contact_options",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "contact_type",
            sa.Enum(
                "whatsapp",
                "snapchat",
                "imessage",
                "telegram",
                "viber",
                "phone",
                "sms",
                name="contact_type",
                schema="roadbuds",
            ),
            nullable=False,
        ),
        sa.Column("contact_value", sa.String(length=120), nullable=False),
        sa.Column("is_preferred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["roadbuds.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("contact_type"),
        schema="roadbuds",
    )
    op.create_table(
        "assistance_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("helper_id", sa.Integer(), nullable=False),
        sa.Column("offered_time", sa.DateTime(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["helper_id"],
            ["roadbuds.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["roadbuds.assistance_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="roadbuds",
    )
    op.create_index(
        "idx_assistance_offers_location",
        "assistance_offers",
        ["location"],
        unique=False,
        schema="roadbuds",
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if True:
        return
    op.drop_index(
        "idx_assistance_offers_location", table_name="assistance_offers", schema="roadbuds", postgresql_using="gist"
    )
    op.drop_table("assistance_offers", schema="roadbuds")
    op.drop_table("user_contact_options", schema="roadbuds")
    op.drop_table("settings", schema="roadbuds")
    op.drop_index(
        "idx_assistance_requests_location", table_name="assistance_requests", schema="roadbuds", postgresql_using="gist"
    )
    op.drop_table("assistance_requests", schema="roadbuds")
    op.drop_table("users", schema="roadbuds")
    op.drop_table("assistance_types", schema="roadbuds")
    # ### end Alembic commands ###
